# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0482049b2e5349ce13ad50d84dd43aca2115f3f3bf0991e36656007b7a4574eed02bb5b8da35123fade92f39f32b690eb8cd67be077dd99cfc6aa2737e21486

test:
  secret_key_base: 953951ac758434c60b1506c5b8b35ceed14e3c5e0aeb3398137b5ab8e9f12a120cd8b5306847f85aa3372bf57e9429c6611e56fa57dec90378b47c0ebf85ac99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
